# -*- coding: utf-8 -*-
"""Jogo_Chute_Numero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dp9yPPqyVRI4z9BYMdxpTSB1lTka-EU9
"""

import random  # importa a biblioteca random para gerar números aleatórios
valor_aleatório = random.randint(1, 20)  # gera um valor aleatório entre 1 e 10
acertou = False  # variável de controle para o loop
tentativas = 0  # variável de controle para o número de tentativas
while not acertou:  # enquanto não acertou
   try:  # Tenta executar o código dentro do bloco try
      chute = int(input('Chute um Valor Inteiro entre 1 e 20: '))
      tentativas += 1  # incrementa o número de tentativas, é a mesma coisa que tentativas = tentativas + 1
      if chute > valor_aleatório:   # se o chute for maior que o valor aleatório gerado no início do programa
              print("Chute foi maior que o valor gerado")
      elif chute < valor_aleatório:   # se o chute for menor que o valor aleatório gerado no início do programa
              print("Chute foi menor que o valor gerado")
      else:
              print(f"Você acertou em {tentativas} tentativa(s)!")
              break    # o valor aleatório gerado no início do programa foi chutado corretamente!
   except ValueError: # Se a entrada não for um número válido, exibe uma mensagem de erro
          print("Entrada inválida. Por favor, tente novamente.")